<?php

use yii\db\Schema;
use yii\db\Migration;

class m150613_123824_init extends Migration
{
    public function up()
    {

        $this->execute("-- MySQL Script generated by MySQL Workbench
-- 06/14/15 12:42:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pathologylab
-- -----------------------------------------------------
-- Pathology Lab schema
--
DROP SCHEMA IF EXISTS `pathologylab` ;

-- -----------------------------------------------------
-- Schema pathologylab
--
-- Pathology Lab schema
--
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pathologylab` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `pathologylab` ;

-- -----------------------------------------------------
-- Table `pathologylab`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pathologylab`.`user` ;

CREATE TABLE IF NOT EXISTS `pathologylab`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `username` VARCHAR(100) NOT NULL COMMENT 'User Name',
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'Password',
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL COMMENT 'Email',
  `age` INT NULL COMMENT 'Age',
  `phone_no` VARCHAR(45) NULL COMMENT 'Phone No',
  `Address` VARCHAR(1000) NULL COMMENT 'Address',
  `visited_on` TIMESTAMP NULL COMMENT 'Visited On',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created Date Time',
  `type` VARCHAR(45) NULL COMMENT 'User Type',
  `delete` SMALLINT NULL DEFAULT 0 COMMENT 'soft delete',
  `status` SMALLINT NULL DEFAULT 1 COMMENT 'Account Status',
  `update_at` TIMESTAMP NULL COMMENT 'Updated On',
  `created_by` BIGINT NULL COMMENT 'Created By User',
  `remark` TEXT NULL COMMENT 'Remark',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `password_reset_token_UNIQUE` (`password_reset_token` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `pathologylab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `pathologylab`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pathologylab`.`report` ;

CREATE TABLE IF NOT EXISTS `pathologylab`.`report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created Date time',
  `user_id` BIGINT NOT NULL,
  `report_name` VARCHAR(45) NULL COMMENT 'Report Name',
  `file_name` VARCHAR(45) NULL COMMENT 'Report File Name',
  `delete` SMALLINT NULL DEFAULT 0 COMMENT 'delete',
  `status` SMALLINT NULL DEFAULT 0 COMMENT 'Status',
  `result_at` TIMESTAMP NULL COMMENT 'Result Date Time',
  `doctor ref` VARCHAR(100) NULL COMMENT 'Doctor reference',
  `remarks` TEXT NULL COMMENT 'Remarks',
  PRIMARY KEY (`id`),
  INDEX `fk_report_user_idx` (`user_id` ASC),
  INDEX `ind_report_name` (`report_name` ASC),
  INDEX `ind_create_at` (`created_at` ASC),
  CONSTRAINT `fk_report_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pathologylab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `pathologylab`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pathologylab`.`test` ;

CREATE TABLE IF NOT EXISTS `pathologylab`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Test Id',
  `name` VARCHAR(100) NULL COMMENT 'Test Name',
  `type` VARCHAR(100) NULL COMMENT 'Test type',
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Added date time',
  `delete` SMALLINT NULL DEFAULT 0,
  `update_at` VARCHAR(45) NULL,
  `created_by` BIGINT NULL COMMENT 'Create by',
  `unit` VARCHAR(45) NULL COMMENT 'Unit',
  `reference` TEXT NULL COMMENT 'Reference Range',
  `remark` TEXT NULL COMMENT 'Remark',
  PRIMARY KEY (`id`),
  INDEX `ind_name` (`name` ASC),
  INDEX `ind_type` (`type` ASC),
  UNIQUE INDEX `comp_unique_name_type` USING BTREE (`type` ASC, `name` ASC),
  INDEX `fk_test_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_test_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `pathologylab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `pathologylab`.`report_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pathologylab`.`report_result` ;

CREATE TABLE IF NOT EXISTS `pathologylab`.`report_result` (
  `report_id` BIGINT NOT NULL,
  `test_id` INT NOT NULL,
  `result` FLOAT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create At',
  `delete` SMALLINT NULL DEFAULT 0,
  PRIMARY KEY (`report_id`, `test_id`),
  INDEX `fk_report_has_test_test1_idx` (`test_id` ASC),
  INDEX `fk_report_has_test_report1_idx` (`report_id` ASC),
  CONSTRAINT `fk_report_has_test_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `pathologylab`.`report` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_report_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `pathologylab`.`test` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

USE `pathologylab` ;

-- -----------------------------------------------------
-- Placeholder table for view `pathologylab`.`detail_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pathologylab`.`detail_report` (`id` INT, `created_at` INT, `user_id` INT, `report_name` INT, `file_name` INT, `delete` INT, `status` INT, `result_at` INT, `doctor ref` INT, `remarks` INT, `name` INT, `type` INT, `unit` INT, `reference` INT, `result` INT);

-- -----------------------------------------------------
-- View `pathologylab`.`detail_report`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `pathologylab`.`detail_report` ;
DROP TABLE IF EXISTS `pathologylab`.`detail_report`;
USE `pathologylab`;
CREATE  OR REPLACE VIEW `detail_report` AS
select
r.*,t.name,t.type,t.unit,t.reference,rs.result
from
report r, report_result rs, test t
where
t.id=rs.test_id and rs.report_id=r.id
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pathologylab`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `pathologylab`;
INSERT INTO `pathologylab`.`user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `age`, `phone_no`, `Address`, `visited_on`, `created_at`, `type`, `delete`, `status`, `update_at`, `created_by`, `remark`) VALUES (1, 'admin', NULL, '0192023a7bbd73250516f069df18b500', NULL, 'admin@pathology.com', NULL, '3123123', 'abc', NULL, '2015-06-14 00:03:09', 'user', 0, 1, '2015-06-14 00:03:09', NULL, NULL);
INSERT INTO `pathologylab`.`user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `age`, `phone_no`, `Address`, `visited_on`, `created_at`, `type`, `delete`, `status`, `update_at`, `created_by`, `remark`) VALUES (2, 'patient', NULL, 'c63f24079f1d5e4cae3fdc1a29116a7b', NULL, 'patient@gmail.com', NULL, '213123', 'abc', '2015-06-14 00:03:09', '2015-06-14 00:03:09', 'patient', 0, 1, '2015-06-14 00:03:09', 1, NULL);
INSERT INTO `pathologylab`.`user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `age`, `phone_no`, `Address`, `visited_on`, `created_at`, `type`, `delete`, `status`, `update_at`, `created_by`, `remark`) VALUES (3, 'patient1', NULL, 'c63f24079f1d5e4cae3fdc1a29116a7b', NULL, 'patient1@gmail.com', NULL, '12312312312', 'abc', '2015-06-14 00:03:09', '2015-06-14 00:03:09', 'patient', 0, 1, '2015-06-14 00:03:09', 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pathologylab`.`report`
-- -----------------------------------------------------
START TRANSACTION;
USE `pathologylab`;
INSERT INTO `pathologylab`.`report` (`id`, `created_at`, `user_id`, `report_name`, `file_name`, `delete`, `status`, `result_at`, `doctor ref`, `remarks`) VALUES (1, '2015-06-14 00:03:09', 2, 'Sample Report', NULL, 0, 1, '2015-06-14 00:03:09', 'Doctor A', 'patient fine');
INSERT INTO `pathologylab`.`report` (`id`, `created_at`, `user_id`, `report_name`, `file_name`, `delete`, `status`, `result_at`, `doctor ref`, `remarks`) VALUES (2, '2015-06-14 00:03:09', 3, 'Sample Report 2', NULL, 0, 1, '2015-06-14 00:03:09', 'Doctor A', 'patient fine');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pathologylab`.`test`
-- -----------------------------------------------------
START TRANSACTION;
USE `pathologylab`;
INSERT INTO `pathologylab`.`test` (`id`, `name`, `type`, `create_at`, `delete`, `update_at`, `created_by`, `unit`, `reference`, `remark`) VALUES (1, 'test 1', 'Type A', '2015-06-14 00:03:09', 0, '2015-06-14 00:03:09', 1, 'mg/dL', 'normal 1-5 bad > 5', NULL);
INSERT INTO `pathologylab`.`test` (`id`, `name`, `type`, `create_at`, `delete`, `update_at`, `created_by`, `unit`, `reference`, `remark`) VALUES (2, 'test 2', 'Type A', '2015-06-14 00:03:09', 0, '2015-06-14 00:03:09', 1, 'a/b', 'normal 1-5 bad > 5', NULL);
INSERT INTO `pathologylab`.`test` (`id`, `name`, `type`, `create_at`, `delete`, `update_at`, `created_by`, `unit`, `reference`, `remark`) VALUES (3, 'test 3', 'Type A', '2015-06-14 00:03:09', 0, '2015-06-14 00:03:09', 1, 'b/c', 'normal 1-5 bad > 5', NULL);
INSERT INTO `pathologylab`.`test` (`id`, `name`, `type`, `create_at`, `delete`, `update_at`, `created_by`, `unit`, `reference`, `remark`) VALUES (4, 'test 4', 'Type B', '2015-06-14 00:03:09', 0, '2015-06-14 00:03:09', 1, 'd/e', 'normal 1-5 bad > 5', NULL);
INSERT INTO `pathologylab`.`test` (`id`, `name`, `type`, `create_at`, `delete`, `update_at`, `created_by`, `unit`, `reference`, `remark`) VALUES (5, 'test 5', 'Type B', '2015-06-14 00:03:09', 0, '2015-06-14 00:03:09', 1, 'r/f', 'normal 1-5 bad > 5', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pathologylab`.`report_result`
-- -----------------------------------------------------
START TRANSACTION;
USE `pathologylab`;
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (1, 1, 4.4, '2015-06-14 00:03:09', 0);
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (1, 2, 3.4, '2015-06-14 00:03:09', 0);
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (1, 3, 5.0, '2015-06-14 00:03:09', 0);
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (2, 1, 3, '2015-06-14 00:03:09', 0);
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (2, 2, 4, '2015-06-14 00:03:09', 0);
INSERT INTO `pathologylab`.`report_result` (`report_id`, `test_id`, `result`, `created_at`, `delete`) VALUES (2, 3, 5, '2015-06-14 00:03:09', 0);

COMMIT;



");
    }

    public function down()
    {
        echo "m150613_123824_init cannot be reverted.\n";

        return false;
    }
    
    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }
    
    public function safeDown()
    {
    }
    */
}
